# Generated by Django 3.2 on 2023-11-16 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=250)),
                ('MedicinePrice', models.IntegerField(max_length=250)),
                ('manufactured_at', models.DateTimeField(default=datetime.datetime(2023, 11, 16, 10, 14, 47, 465404))),
            ],
        ),
    ]
