# Generated by Django 3.2 on 2023-11-29 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_list_manufactured_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('PhoneNumber', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 5, 8, 40, 465114)),
        ),
    ]
