# Generated by Django 3.2 on 2023-11-29 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20231129_0536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regis',
        ),
        migrations.AlterField(
            model_name='list',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 5, 53, 43, 883986)),
        ),
    ]
