# Generated by Django 3.2 on 2023-11-29 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20231129_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 7, 31, 9, 249059)),
        ),
    ]
