# Generated by Django 3.2 on 2023-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_auto_20231205_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='ExpiredDate',
            field=models.DateField(),
        ),
    ]
